### ISSUE TITLE
Question about the running speed of Pyflann and Faiss  for the SAM model

### ISSUE THREAD

**Issue by zoharli** [ixaxaar/pytorch-dnc#40]
I can't normally install Faiss environment because of certain force majeure, so I wonder how using Faiss-gpu or Pyflann will influence the actual training speed of the SAM model.
Let's say for example, in the copy task, how are the actual epoch times when using these two methods?  Can you give me a rough reference?

**Comment by ixaxaar** [comment]
Oh it was significant enough that I had to literally shove FAISS in this project. 

I mean the first version I had implemented was using flann, but FAISS was just way faster. In fact I ended up keeping flann just in case (as some kind of a fallback).

**Comment by zoharli** [comment]
Ok, I get it now, thanks！

**Comment by ixaxaar** [comment]
Cool! Closing this issue then 😬
