### ISSUE TITLE
Error when running copy_task.py

### ISSUE THREAD

**Issue by jin8** [ixaxaar/pytorch-dnc#48]
I executed copy task as following the cmd line in README.
python copy_task.py -cuda 0 -optim rmsprop -batch_size 32 -mem_slot 64 
Having NameError at line 366, name 'input_size' is not defined.
I can change the input_size to args.input_size, but I think there are additional problems other than that.
Function generate_data at requires 3 arguments, but only 2 are given. 
Is generate_data in line 366 a different function defined in line 78?

https://github.com/ixaxaar/pytorch-dnc/blob/016b541223bf801f3f3a617fa3942cc12ef71be9/tasks/copy_task.py#L78
https://github.com/ixaxaar/pytorch-dnc/blob/016b541223bf801f3f3a617fa3942cc12ef71be9/tasks/copy_task.py#L366

Thank you,

**Comment by ixaxaar** [comment]
Thanks for the report, refer to #47
