### ISSUE TITLE
reset_experience meaning

### ISSUE THREAD

**Issue by smorad** [ixaxaar/pytorch-dnc#58]
Looking at the code it isn't clear to me what `reset_experience` does. Since the memory is an argument to the `forward`, is setting `reset_experience` equivalent to calling `dnc(controller_state, None, read_vectors)`?

If this is the case, then when using dnc with inputs of shape `[batch, time, feature]` , `reset_experience` will clear the memory between batches. If we continuously call dnc with inputs of shape `[batch, 1, feature]`, then we do not want to reset. Is this correct?

**Comment by ixaxaar** [comment]
You're right, reset_experience is a switch to clear memory per batch.
> we do not want to reset.
Well that is up to you, i was using it as a flag for experiments
