### ISSUE TITLE
Write unit tests

### ISSUE THREAD

**Issue by ixaxaar** [ixaxaar/pytorch-dnc#8]

**Comment by MaxwellRebo** [comment]
What kinds of unit tests were you thinking? And which testing framework (if any)?

**Comment by MaxwellRebo** [comment]
Just saw the commit. Answers my question. 😄

**Comment by ixaxaar** [comment]
@MaxwellRebo right now, I just wrote some quick ones which check if the output, hidden etc dimensions are correct

**Comment by ixaxaar** [comment]
I find myself making too many changes as this is still a quite initial phase, I'd want stuff to not break outright. Also integrating travis helps encourage write more detailed tests later on.
